### ISSUE TITLE
Avoid set styles directly in JS

### ISSUE THREAD

**Issue by joostf** [follywolly/web-app-from-scratch-18-19#10]
instead use custom properties

https://github.com/follywolly/web-app-from-scratch-18-19/blob/129e3c7de7e32b32a2eef8e74dfca60315437b4b/src/js/modules/render.js#L44

**Comment by folkertjan** [comment]
Not really sure that would work since it's unknown how many colors the API can give back. This line is used to generate small divs that show the colors the artwork exists of. 
Pretty sure I can't generate all necessary css variables and enough css rules in my css file to make that happen dynamically, right?

**Comment by joostf** [comment]
I would think, one custom variable (--color) should be enough? Or am I not thinking straight?

**Comment by folkertjan** [comment]
Well you would need a custom variable for each color, otherwise the divs that are supposed to represent (for example) 6 different colors would end up having the same color right?

**Comment by joostf** [comment]
Yeah, I think you’re right!


Op 8 feb. 2019 om 15:51 heeft Folkert-Jan <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Well you would need a custom variable for each color, otherwise the divs that are supposed to represent (for example) 6 different colors would end up having the same color right?

**Comment by folkertjan** [comment]
The only way I can think of making that work is to make as many css variables as there are colors returned from the api within a js loop. Gonna look in to that.

**Comment by joostf** [comment]
I’m gonna think about it some more aswell

Gr. Joost

Op 8 feb. 2019 om 16:56 heeft Folkert-Jan <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


The only way I can think of making that work is to make as many css variables as there are colors returned from the api within a js loop. Gonna look in to that.
