### ISSUE TITLE
Api-key zichtbaar

### ISSUE THREAD

**Issue by DanielvandeVelde** [follywolly/web-app-from-scratch-18-19#12]
https://github.com/follywolly/web-app-from-scratch-18-19/blob/129e3c7de7e32b32a2eef8e74dfca60315437b4b/src/js/modules/data.js#L2

Op dit moment is je api-key zichtbaar.
Je kan dit het beste even wijzigen aangezien dit gevoelige informatie is.
Hoe je dan kan doen is onder andere [hier](https://gist.github.com/derzorngottes/3b57edc1f996dddcab25) te vinden.

**Comment by folkertjan** [comment]
No problem in this assignment.
