### ISSUE TITLE
RIP

### ISSUE THREAD

**Issue by rijkvanzanten** [follywolly/web-app-from-scratch-18-19#16]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/9141017/53839633-0f743980-3f66-11e9-9f80-4f1557ba7185.png">

**Comment by rijkvanzanten** [comment]
https://follywolly.github.io/web-app-from-scratch-18-19/src/#/ does work however

**Comment by folkertjan** [comment]
Fixed in README and project description link
