### ISSUE TITLE
IIFE

### ISSUE THREAD

**Issue by Arash217** [follywolly/web-app-from-scratch-18-19#6]
https://github.com/follywolly/web-app-from-scratch-18-19/blob/129e3c7de7e32b32a2eef8e74dfca60315437b4b/src/js/app.js#L9

IIFE can be an anonymous function.

**Comment by folkertjan** [comment]
That already is an anonymous function. 
If you are talking about an arrow function, there was an issue already closed which suggested to replace it with an arrow function.

**Comment by Arash217** [comment]
Yeah, I meant an anonymous arrow function 😅

**Comment by folkertjan** [comment]
Right, that was already fixed. Thanks anyway
