### ISSUE TITLE
Cache stuff (e.g. dom elements) in variables 

### ISSUE THREAD

**Issue by joostf** [follywolly/web-app-from-scratch-18-19#7]
for better efficiency and readablility

https://github.com/follywolly/web-app-from-scratch-18-19/blob/129e3c7de7e32b32a2eef8e74dfca60315437b4b/src/js/app.js#L22

**Comment by folkertjan** [comment]
Interesting, why would I do that if the change to this dom element only happens once in this document? Wouldn't making a seperate var for one action be a (very, very slight) waste in memory?

**Comment by joostf** [comment]
In this case because of readability (and consistency)
It could be a best practice: 'Always store dom elements in variables'?

**Comment by folkertjan** [comment]
Hmm okay. Implemented!
