### ISSUE TITLE
Use config object

### ISSUE THREAD

**Issue by joostf** [follywolly/web-app-from-scratch-18-19#8]
https://github.com/follywolly/web-app-from-scratch-18-19/blob/129e3c7de7e32b32a2eef8e74dfca60315437b4b/src/js/modules/data.js#L4-L8

**Comment by folkertjan** [comment]
I mean, they are two different urls so I figured i might as well write it like this. I could make it a return value from a function where the necessary changes can be parameters I guess.

**Comment by joostf** [comment]
You can start with storing the endpoint bit in an endpoint property ('https://www.rijksmuseum.nl/api/nl/collection'). 

Again it's better for readability, and makes it easier to build different api urls for future scenarios

**Comment by folkertjan** [comment]
Seems legit!
