### ISSUE TITLE
Use better name?

### ISSUE THREAD

**Issue by joostf** [follywolly/web-app-from-scratch-18-19#9]
E.g. _overview_, in case you want to render an overview of items on other pages than the homepage?

https://github.com/follywolly/web-app-from-scratch-18-19/blob/129e3c7de7e32b32a2eef8e74dfca60315437b4b/src/js/modules/render.js#L6

**Comment by folkertjan** [comment]
This was just for purposes to make the basic router. All these routes will be refactored so this will be removed anyway

**Comment by joostf** [comment]
fair enough!
